#!/bin/bash
pip install --upgrade virtualenv
pip install --upgrade pip
conda env create -f environment.yml
source activate myenv
pip install -r requirements.txt
pip install pypfopt
pip install nltk
python -m nltk.downloader vader_lexicon
chmod +x binder/start
./binder/start
