#!/bin/bash
sudo pip3 install --upgrade pip
sudo pip3 install virtualenv
curl https://bootstrap.pypa.io/get-pip.py | python
conda env create -f environment.yml
source activate myenv
pip install -r requirements.txt
pip install pypfopt
pip install nltk
python -m nltk.downloader vader_lexicon
chmod +x binder/start
./binder/start
